$(document).ready(function(){
/*$("#hide").click(function(){
	$('#hide').hide('1000');	
});
$("div").click(function(){
	$("#disappear").toggle('slow');
});
$("div").click(function(){
	$("#disappear").slideToggle('fast');
});
$("#hide").mouseenter(function(){
	$("#hide").fadeTo(1000,0.5);
});
$("#hide").mouseleave(function(){
	$("#hide").fadeTo(1000,1);
});*/
$("div").mouseenter(function(){
$(this).removeClass("makeRed").addClass("makeBorder")
});
$("div").mouseleave(function(){
$(this).addClass("makeRed").removeClass("makeBorder")
});
$("div").click(function(){
	$("#disappear").slideUp('fast').slideDown('slow');
});
});
